steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  # Environment variables specifically for the 'build' step
  env:
  - 'NEXT_PUBLIC_MY_ENV_VAR=${NEXT_PUBLIC_MY_ENV_VAR}'
  - 'ANOTHER_BUILD_VAR=${_MY_CUSTOM_BUILD_SECRET}' # Using a substitution variable
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'gcr.io/$PROJECT_ID/my-nextjs-app:$COMMIT_SHA', '.']
images:
- 'gcr.io/$PROJECT_ID/my-nextjs-app:$COMMIT_SHA'

