steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Write your entire .env from Secret Manager into .env
        echo "$ENV_FILE" > .env

        # Build and tag the image, passing NEXT_PUBLIC_… vars as build-args
        docker build \
          --build-arg NEXT_PUBLIC_VAR1="$NEXT_PUBLIC_VAR1" \
          --build-arg NEXT_PUBLIC_VAR2="$NEXT_PUBLIC_VAR2" \
          -t "$IMAGE" \
          .

availableSecrets:
  secretManager:
    - versionName: "projects/565291147090/secrets/test-deploy/versions/latest"
      env: "ENV_FILE"

images:
  - "$IMAGE"
